### ISSUE TITLE
Feature Request: Add security layer to prevent external builds to be deployed

### ISSUE THREAD

**Issue by PaoloAtRebelpug** [alanlawrance/steam-deploy-public#1]
Hello there,

thanks for your wonderful work!

I was thinking of a possible wrong situation that could happen:
Someone find out your url for the automatic build and publish a different game in your depot. Is it possible to happen right? In that case, I saw that Unity Cloud Build has the possibility to pass an Auth Secret, would you consider implementing a security layer to protect from this situation?

Thanks,
Paolo

**Comment by alanlawrance** [comment]
You are right, this could happen.  It should be protected against, and your thoughts on it sound good.

**Comment by PaoloAtRebelpug** [comment]
Do you have any recommended approach on this? I am not much of an expert on this topic

**Comment by alanlawrance** [comment]
I don't have any recommended approaches... would need to do some research first.

**Comment by alanlawrance** [comment]
So the EC2 configuration requires you to configure security rules for inbound traffic.  Currently the documentation says to select "Anywhere" as the Source, but we may be able to set the Source as the Unity Cloud Build servers.  I am following up with Unity about this.

**Comment by PaoloAtRebelpug** [comment]
Yes that could be an option. I was thinking if it was worth to do something provider agnostic. Maybe some internal authorization process. Doing it this way we wouldn't lock users to AWS. What do you think?

**Comment by alanlawrance** [comment]
Pull request for this feature merged, thank you!
