### ISSUE TITLE
Feature Request: Rotating log file

### ISSUE THREAD

**Issue by PaoloAtRebelpug** [alanlawrance/steam-deploy-public#2]
Hello there,

again wonderful work!

I was testing the integration with your application and I need to keep listening to pm2 logs. What do you thinkg about implementing a rotating log file creation? 

The rule could be the following:
Every day rotate the file
If a file is older than two weeks delete it

Thanks,
Paolo

**Comment by alanlawrance** [comment]
It may be cleaner to just configure pm2 to have a maximum log file size.  Quick google search turns this up:

https://github.com/keymetrics/pm2-logrotate

Can be installed with:

pm2 install pm2-logrotate

The default size is 10MB, but can be configured.

I lean towards updating the documentation to recommend limiting the log size for pm2 using this.

**Comment by PaoloAtRebelpug** [comment]
That is true, it would be simplier but in that case I would suggest changing the documentation for starting the app with timestamp in the logs like is suggested here: [](https://stackoverflow.com/questions/21317852/how-to-add-dates-to-pm2-error-logs)

**Comment by alanlawrance** [comment]
Sounds good, I'll update documentation with both of these items and then close this.

**Comment by alanlawrance** [comment]
Added "PM2 Configuration" section to documentation.
