### ISSUE TITLE
Bug: Passwords with special chars won't login

### ISSUE THREAD

**Issue by PaoloAtRebelpug** [alanlawrance/steam-deploy-public#4]
How to replicate:

Create user with password with special chars, try to upload a build using the script, it will fail the login.

Solution:
Instead of 
`${steamcmd} +login ${username} ${password} +run_app_build ${appvdf} +quit`

Use
`${steamcmd} +login ${username} '${password}' +run_app_build ${appvdf} +quit`

**Comment by alanlawrance** [comment]
Thanks, fix made in main.
